// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACyE7SoIYgt6cSSFqX2YDWZxoCLaU39Ok',
    appId: '1:387056517791:web:2be4286c983f6d01a098aa',
    messagingSenderId: '387056517791',
    projectId: 'firechatpro-91884',
    authDomain: 'firechatpro-91884.firebaseapp.com',
    databaseURL: 'https://firechatpro-91884-default-rtdb.firebaseio.com',
    storageBucket: 'firechatpro-91884.firebasestorage.app',
    measurementId: 'G-RWPHSC2QB2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5MAIAaIhtXwuzWCRWFGi1c1Cdha4rItg',
    appId: '1:282231451432:android:6a6650d67127903d056a1d',
    messagingSenderId: '282231451432',
    projectId: 'ptt-communicator',
    databaseURL: 'https://ptt-communicator-default-rtdb.firebaseio.com',
    storageBucket: 'ptt-communicator.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV2ZSJN4MG32dQmqYaFz6DOA4JHkRnb40',
    appId: '1:282231451432:ios:9a1492027d418415056a1d',
    messagingSenderId: '282231451432',
    projectId: 'ptt-communicator',
    databaseURL: 'https://ptt-communicator-default-rtdb.firebaseio.com',
    storageBucket: 'ptt-communicator.appspot.com',
    androidClientId: '282231451432-9enjcbps5famouq9f6nvu24k5qshqaio.apps.googleusercontent.com',
    iosClientId: '282231451432-7kjr2m7l81khpujt7f8kj3bb7pbmek7f.apps.googleusercontent.com',
    iosBundleId: 'com.pttcommunicate.pttmessenger',
  );

}